[package]
name = "firework"
version = "0.1.0"
edition = "2021"

[lib]
name = "firework"

[dependencies]
moonwalk = { workspace = true }
raw-window-handle = "0.6"
glam = "0.24"
pollster = "0.3"

[target.'cfg(any(target_os = "windows", target_os = "linux", target_os = "macos", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd"))'.dependencies]
winit = "0.29"